- hosts: win
  tasks:
    # create a domain
    - win_domain:
        dns_domain_name: mydomain.local
        safe_mode_password: ItsASecret

    # add a domain user
    - win_domain_user:
        name: somebody
        upn: somebody@mydomain.local
        groups:
          - Domain Admins


