- hosts: win
  gather_facts: no
  tasks:
    # use the domain controller for dns server; not normally needed
    - win_dns_client:
        adapter_names: '*'
        ipv4_addresses: 192.168.33.5

    # join newhost3 to domain mydomain.local
    - win_domain_membership:
        dns_domain_name: mydomain.local
        hostname: newhost3
        domain_admin_user: mydomain\user1
        domain_admin_password: Password123!
        state: domain
      register: dmout
        
    - win_reboot:
      when: dmout.reboot_required


